[#24] EditText 스타일 추가
MoyeoRun/MoyeoRun_Android pull request #25
Opened 2022-03-23 07:45 UTC by gemiJ

## 내용
+ 자주쓰이는 UI인 EditText 스타일을 추가합니다.
  + 테두리 색상, 굵기, 모서리의 반경을 설정했습니다.

## 작업사항
+ focus 상태에 대한 색상 구분이 명시되어있지 않아 임의로 같은 색상으로 설정해두었습니다. 
+ `com.google.android.material.textfield.TextInputLayout`의 스타일로 설정하여 사용합니다.

2022-03-24 11:23 UTC, DongJun-H requested changes

2022-03-24 11:23 UTC, DongJun-H commented on app/src/main/res/values/colors.xml
> +    <color name="edittext_default_stroke">#DCDDDF</color>
얼른 컬러가 정해지면 좋겠네요^.^.....

2022-03-24 11:23 UTC, DongJun-H commented on app/src/main/res/values/themes.xml
> +        <item name="cornerRadius">@dimen/defaultEditTextRadius</item>
themes.xml에서 관리하는 것보다 따로 customview에 대한 style을 모아놓은 xml 파일로 나눠서 관리하는거 어떨까요?

(사실 제가 이전 커밋을 수정하면서 만들었습니다)

2022-03-24 14:37 UTC, choheeis commented
메인 커스텀 뷰에 대한 PR이 별도로 올라왔는데 본 PR에도 동일한 코드가 커밋된 것 같습니다! EditText에 대한 코드만 있어야 할 것 같은데 한 번 확인 해주실 수 있을까요 ~?

2022-03-25 08:27 UTC, gemiJ commented
> 메인 커스텀 뷰에 대한 PR이 별도로 올라왔는데 본 PR에도 동일한 코드가 커밋된 것 같습니다! EditText에 대한 코드만 있어야 할 것 같은데 한 번 확인 해주실 수 있을까요 ~?

기존 브랜치에서 브랜치를 만들어서 그렇게 된 것 같네요.. 다시 커밋하겠습니다!

2022-03-25 08:28 UTC, gemiJ commented on app/src/main/res/values/themes.xml
> +        <item name="cornerRadius">@dimen/defaultEditTextRadius</item>
넵~!

2022-03-27 02:32 UTC, winter223 commented
`TextInputLayout`의 스타일을 재정의하는 것으로 끝난다면, 앞으로 이런 테두리 EditText 를 사용할 때 매번 `TextInputLayout`과 `TextInputLayout`과 `TextInputEditText`를 사용해야합니다. 꽤 많이 번거로울 것 같아요.

앞으로 사용할 때에 최대한 간편할 수 있는 방향으로 고민해주시면 좋을 것 같습니다.

개인적으로는 background, textSize, textColor, textColorHint, padding 등만 스타일로 정의해두어도 충분할 것 같습니다.
여기서 background 는 마찬가지로 Shape Drawable 로 구현이 가능하구요.

+) 프로필 편집 화면을 제외하고는 모든 EditText 가 동일하게 테두리를 두르고 있으니, 애초에 저희 기본 테마에 `buttonStyle`을 이걸로 적용해도 되구요. 그럼 앞으로 EditText 만 써도 해당 속성들이 다 적용됩니다.

2022-04-01 17:01 UTC, gemiJ commented
+ shape파일로 `<item name="android:editTextBackground">` 기본 테마를 설정했습니다.  
+ 해당 브랜치와 관련없는 코드를 제거했습니다.

2022-04-03 16:50 UTC, choheeis commented on app/src/main/res/drawable/shape_default_edittext.xml
> +        android:color="#DCDDDF"
피그마 상에서 editText의 테두리 색상이 한 가지가 아니네요..(#D4D4D4도 있는 것으로 확인됩니다. 디자이너 분께 여쭤보는 것도 좋을 것 같습니다.) 그리고 색상은 color 파일에서 관리하는 것이 어떨까요?

2022-04-03 16:50 UTC, choheeis commented on app/src/main/res/drawable/shape_default_edittext.xml
> +        android:color="#DCDDDF"
(+ radius도 4dp인 곳도 있네요. 디자이너 분께 통일을 하는 것이 가능할지? 통일이 안 되는 것인지(의도된 것인지) 여쭤보는 것도 좋을 것 같아요~!)

2022-04-03 16:50 UTC, choheeis commented on app/src/main/res/values/colors.xml
> +
이 부분도 본 PR에서는 사용되지 않는 것 같습니다!

2022-04-03 16:51 UTC, choheeis commented
제 개인 테스트 폰인 Android 9에서 EditText의 테두리가 적용되지 않는 것 같습니다. 😂 
<img src="https://user-images.githubusercontent.com/31889335/161438491-fcd730ba-8a7a-4964-92c4-2f560dac63e8.png" width="300" />

2022-04-07 03:04 UTC, winter223 commented on app/src/main/res/drawable/shape_default_edittext.xml
> +        android:color="#DCDDDF"
요건 물어봐야겠네요 ~

2022-04-15 15:36 UTC, winter223 approved these changes
기본 테마에 속성을 먹이는 게 잘 되지 않으니, 그냥 스타일만 따로 정의하고 마무리하면 좋을 것 같습니다.
다른 PR 에서 논의된대로 styles_edittext 하나 만드시고, 거기다가 BorderEditText 쯔음의 이름으로 스타일을 하나 정의해주세요. 배경에는 작성하신 shape drawable 이 들어가면 될듯합니다.

+) 아 그리고 default 라는 네이밍보다는 border 라는 네이밍이 좋아보입니다 ㅎㅎ

2022-04-16 02:54 UTC, gemiJ commented
> 기본 테마에 속성을 먹이는 게 잘 되지 않으니, 그냥 스타일만 따로 정의하고 마무리하면 좋을 것 같습니다. 다른 PR 에서 논의된대로 styles_edittext 하나 만드시고, 거기다가 BorderEditText 쯔음의 이름으로 스타일을 하나 정의해주세요. 배경에는 작성하신 shape drawable 이 들어가면 될듯합니다.
> 
> +) 아 그리고 default 라는 네이밍보다는 border 라는 네이밍이 좋아보입니다 ㅎㅎ

피그마 상에 EditText의 스타일이 다양해서 질문을 남겼는데, 해당 내용에 대한 답변이 달리면 작업하려 했습니다! 답변 달리는 대로 border이라는 네이밍을 적용해서 커밋하겠습니다.

2022-04-25 18:04 UTC, DongJun-H approved these changes
EditText Style로 잘 적용되는것 같습니다^.^ 수고하셨어요!

2022-04-30 14:05 UTC, choheeis approved these changes
컨플릭 해결해 주시고 머지해주시면 될 것 같습니다~~ 수고하셨습니당 EditText 잘 사용할게요!

2022-05-01 12:56 UTC, merged